dataset:
    src: # path/to/dataset
    class_mode: binary
    classes: 
        - # class 1
        - # class 2
    batch: 128
    class_options:
        # additional options for initalizing model class
    compile_options:
        # additional options for compiling model
model:
    name: # my_new_model
    module: tensorflow.keras.applications.resnet
    class: ResNet50
    weights: imagenet
    checkpoints: # /path/to/checkpoints
optimizer:
    module: tensorflow.keras.optimizers
    class: Nadam
    options:
        learning_rate: 0.001
        beta_1: 0.9
        beta_2: 0.999
        epsilon: 0.0000001
callbacks:
    ReduceLROnPlateau:
        monitor: val_loss
        mode: min
        patience: 5
        factor: 0.5
        min_lr: 0.000001
        verbose: 1
    EarlyStopping:
        monitor: val_loss
        mode: min
        patience: 10
        restore_best_weights: True
        verbose: 1
training:
    epochs: 10
    options:
        # additional options for training model
    