dataset:
    src: # path/to/dataset
    class_mode: binary
    classes: 
        - # class 1
        - # class 2
    batch: 128
model:
    module: tensorflow.keras.applications.resnet
    class: ResNet50
    weights: imagenet
    checkpoints: # /path/to/checkpoints
optimizer:
    module: tensorflow.keras.optimizers
    class: Nadam
    options:
        learning_rate: 0.001
        beta_1: 0.9
        beta_2: 0.999
        epsilon: 0.0000001
    